/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherScheduleRouteImport } from './routes/teacher.schedule'
import { Route as TeacherPaymentsRouteImport } from './routes/teacher.payments'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherLessonReportRouteImport } from './routes/teacher.lesson-report'
import { Route as ParentScheduleRouteImport } from './routes/parent.schedule'
import { Route as ParentReportsRouteImport } from './routes/parent.reports'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as TeacherStudentsIndexRouteImport } from './routes/teacher.students.index'
import { Route as TeacherStudentsStudentIdRouteImport } from './routes/teacher.students.$studentId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherScheduleRoute = TeacherScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPaymentsRoute = TeacherPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLessonReportRoute = TeacherLessonReportRouteImport.update({
  id: '/lesson-report',
  path: '/lesson-report',
  getParentRoute: () => TeacherRoute,
} as any)
const ParentScheduleRoute = ParentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ParentRoute,
} as any)
const ParentReportsRoute = ParentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ParentRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsIndexRoute = TeacherStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherStudentsRoute,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => TeacherStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parent': typeof ParentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/teacher/lesson-report': typeof TeacherLessonReportRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/payments': typeof TeacherPaymentsRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRouteWithChildren
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/teacher/lesson-report': typeof TeacherLessonReportRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/payments': typeof TeacherPaymentsRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/parent': typeof ParentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/students': typeof TeacherStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parent': typeof ParentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/teacher/lesson-report': typeof TeacherLessonReportRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/payments': typeof TeacherPaymentsRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRouteWithChildren
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parent'
    | '/teacher'
    | '/invite/$token'
    | '/parent/reports'
    | '/parent/schedule'
    | '/teacher/lesson-report'
    | '/teacher/messages'
    | '/teacher/payments'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/parent/'
    | '/teacher/'
    | '/teacher/students/$studentId'
    | '/teacher/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/parent/reports'
    | '/parent/schedule'
    | '/teacher/lesson-report'
    | '/teacher/messages'
    | '/teacher/payments'
    | '/teacher/schedule'
    | '/parent'
    | '/teacher'
    | '/teacher/students/$studentId'
    | '/teacher/students'
  id:
    | '__root__'
    | '/'
    | '/parent'
    | '/teacher'
    | '/invite/$token'
    | '/parent/reports'
    | '/parent/schedule'
    | '/teacher/lesson-report'
    | '/teacher/messages'
    | '/teacher/payments'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/parent/'
    | '/teacher/'
    | '/teacher/students/$studentId'
    | '/teacher/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentRoute: typeof ParentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/schedule': {
      id: '/teacher/schedule'
      path: '/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof TeacherScheduleRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/payments': {
      id: '/teacher/payments'
      path: '/payments'
      fullPath: '/teacher/payments'
      preLoaderRoute: typeof TeacherPaymentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/lesson-report': {
      id: '/teacher/lesson-report'
      path: '/lesson-report'
      fullPath: '/teacher/lesson-report'
      preLoaderRoute: typeof TeacherLessonReportRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/parent/schedule': {
      id: '/parent/schedule'
      path: '/schedule'
      fullPath: '/parent/schedule'
      preLoaderRoute: typeof ParentScheduleRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/reports': {
      id: '/parent/reports'
      path: '/reports'
      fullPath: '/parent/reports'
      preLoaderRoute: typeof ParentReportsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students/': {
      id: '/teacher/students/'
      path: '/'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof TeacherStudentsIndexRouteImport
      parentRoute: typeof TeacherStudentsRoute
    }
    '/teacher/students/$studentId': {
      id: '/teacher/students/$studentId'
      path: '/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof TeacherStudentsRoute
    }
  }
}

interface ParentRouteChildren {
  ParentReportsRoute: typeof ParentReportsRoute
  ParentScheduleRoute: typeof ParentScheduleRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentReportsRoute: ParentReportsRoute,
  ParentScheduleRoute: ParentScheduleRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface TeacherStudentsRouteChildren {
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherStudentsIndexRoute: typeof TeacherStudentsIndexRoute
}

const TeacherStudentsRouteChildren: TeacherStudentsRouteChildren = {
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherStudentsIndexRoute: TeacherStudentsIndexRoute,
}

const TeacherStudentsRouteWithChildren = TeacherStudentsRoute._addFileChildren(
  TeacherStudentsRouteChildren,
)

interface TeacherRouteChildren {
  TeacherLessonReportRoute: typeof TeacherLessonReportRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherPaymentsRoute: typeof TeacherPaymentsRoute
  TeacherScheduleRoute: typeof TeacherScheduleRoute
  TeacherStudentsRoute: typeof TeacherStudentsRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherLessonReportRoute: TeacherLessonReportRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherPaymentsRoute: TeacherPaymentsRoute,
  TeacherScheduleRoute: TeacherScheduleRoute,
  TeacherStudentsRoute: TeacherStudentsRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentRoute: ParentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
